[build]
  command = "npm install $NPM_FLAGS && npm run build"
  publish = "dist"

[context.production.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[context.deploy-preview.environment]
  NPM_FLAGS = "--legacy-peer-deps"
